apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  mysql-root-password: cm9vdF9wYXNz  # base64 encoded 'root_pass'
  mysql-database: cGRuc19kYg==     # 'pdns_db'
  mysql-user: cGRuc191c2Vy       # 'pdns_user'
  mysql-password: cGRuc19wYXNz     # 'pdns_pass'
